app:
  datasource:
    jdbc-url: jdbc:postgresql://postgresql-silhouetted-32258/d3n7ls4ln31mrm
    username: yqrrlkcrpaphij
    password: f0a6fdf80e6183d6d30a3e80791f727a12293dc86c55bed2efc8d62f9fcb519a
    pool-size: 30

server:
  port: 1122